version: "3.9"

services:
  api:
    build:
      context: ./server
      dockerfile: ./api.dockerfile
    env_file: 
      - .env
    ports:
      - "5000:5000"
    networks:
      - net-iowa-code-camp

  
networks:
  net-iowa-code-camp:
    name: net-iowa-code-camp